# Generated by Django 2.2 on 2020-05-11 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dad_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='last_ame',
            new_name='last_name',
        ),
    ]
